platform:ios, '8.0'

target ‘DouYu’ do
project '/Users/ja/DouYu/DouYu/DouYu.xcodeproj'
use_frameworks! 

pod 'Alamofire', '~> 4.5'
pod 'SnapKit', '~> 4.0.0'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDCycleScrollView', '~> 1.66'
pod 'SDWebImage', '~> 4.0.0'

end

