platform:ios, '8.0'

target ‘DouYu’ do
project '/Users/ja/DouYu/DouYu/DouYu.xcodeproj'
use_frameworks! 

pod 'Alamofire', '~> 4.5'
pod 'SnapKit', '~> 3.2.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'SDCycleScrollView', '~> 1.75'
pod 'SDWebImage', '~> 4.2.2'

end

